### ISSUE TITLE
Yaml does not parse

### ISSUE THREAD

**Issue by philpott** [Rohit-Xapads/Xapads_Tracking_CPS_SDK#1]
https://github.com/Rohit-Xapads/Xapads_Tracking_CPS_SDK/blob/bb1e9a8afad948c2494b3d257bb9085fb7fd0bed/metadata.yaml#L1

I'm attempting to perform the review of the template and your YAML file is not parsing due to the comma after homepage.

**Comment by sandeepxapads** [comment]
Dear Philpott,

Comma is removed. Please refer to the new commit and review them again and let us know.
